__countryGeoBase:
LOAD
	ISO3Code AS [__ISO3Code],
	ISO2Code AS [__ISO2Code],
	Polygon AS [__Polygon]
FROM [lib://AttachedFiles/countryGeo.qvd]
(qvd);

__countryCodeIsoTwo2Polygon:
MAPPING LOAD
	__ISO2Code,
	__Polygon
RESIDENT __countryGeoBase;

LIB CONNECT TO [Sagrosoft (sagro_qsadmin)];

[tblMaterieel]:
LOAD 
	[MaterieelID],
	[CreditorCode],
	[Eigenaar],
	[GebruikerBV],
	[KostenPlaats],
	[Groep],
	[Omschrijving],
	[Kenteken],
	[Inhuur],
	[Actief] AS [tblMaterieel.Actief],
	[GewichtTarra],
	[Laadvermogen],
	[DatumInactiefGezet] AS [tblMaterieel.DatumInactiefGezet],
	[KanLadingZijn],
	[VasteOperator],
	[Aanmaakdatum] AS [tblMaterieel.Aanmaakdatum],
	[Gebruiker] AS [tblMaterieel.Gebruiker],
	[GebruikBijOverslag] AS [tblMaterieel.GebruikBijOverslag],
	[GebruikBijRit] AS [tblMaterieel.GebruikBijRit],
	[GebruikBijUrenRegistratie],
	[GebruikBijStrooien] AS [tblMaterieel.GebruikBijStrooien],
	[Verkocht],
	[VerkoopDatum],
	[VerkochtAan],
	[Verzekerd],
	[Bouwdatum],
	[AankoopDatum],
	[VerkoopNotaBijlage],
	[OpdrachtBevestigingBijlage],
	[KentekenBewijsBijlage],
	[TrackingTracing],
	[TariefIntern] AS [tblMaterieel.TariefIntern],
	[Verbruik],
	[Overdruk],
	[Zoekterm],
	[Garage],
	[Merk],
	[Oplegger];
SELECT MaterieelID, 
	CreditorCode, 
	Eigenaar, 
	GebruikerBV, 
	KostenPlaats, 
	Groep, 
	Omschrijving, 
	Kenteken, 
	Inhuur, 
	Actief, 
	GewichtTarra, 
	Laadvermogen, 
	DatumInactiefGezet, 
	KanLadingZijn, 
	VasteOperator, 
	Aanmaakdatum, 
	Gebruiker, 
	GebruikBijOverslag, 
	GebruikBijRit, 
	GebruikBijUrenRegistratie, 
	GebruikBijStrooien, 
	Verkocht, 
	VerkoopDatum, 
	VerkochtAan, 
	Verzekerd, 
	Bouwdatum, 
	AankoopDatum, 
	VerkoopNotaBijlage, 
	OpdrachtBevestigingBijlage, 
	KentekenBewijsBijlage, 
	TrackingTracing, 
	TariefIntern, 
	Verbruik, 
	Overdruk, 
	Zoekterm, 
	Garage, 
	Merk, 
	Oplegger 
FROM "Sagro_backend".dbo.tblMaterieel;

[tblOpdracht]:
LOAD 
	[OpdrachtID] AS [tblOpdracht.OpdrachtID],
	[OpdrachtNemer],
	[DebiteurCode],
	[Debiteur],
	[OpdrachtDatum],
	[OpdrachtEindDatum],
	[Werknummer] AS [ProjectNr-Werknummer],
	[WerknummerExtern],
	[OpdrachtOmschrijving],
	[OpdrachtStatus],
	[ZiekteUren],
	[ExactStatus],
	[Aanmaakdatum] AS [tblOpdracht.Aanmaakdatum],
	[Gebruiker] AS [tblOpdracht.Gebruiker],
	[GladheidProject],
	[OverslagProject],
	[Projectnummer2],
	[Kostendrager] AS [tblOpdracht.Kostendrager],
	[ExactStatus2];
SELECT OpdrachtID, 
	OpdrachtNemer, 
	DebiteurCode, 
	Debiteur, 
	OpdrachtDatum, 
	OpdrachtEindDatum, 
	Werknummer, 
	WerknummerExtern, 
	OpdrachtOmschrijving, 
	OpdrachtStatus, 
	ZiekteUren, 
	ExactStatus, 
	Aanmaakdatum, 
	Gebruiker, 
	GladheidProject, 
	OverslagProject, 
	Projectnummer2, 
	Kostendrager, 
	ExactStatus2 
FROM "Sagro_backend".dbo.tblOpdracht;

[tblPersoneel]:
LOAD 
	[PersoneelID],
	[PersoneelNo],
	[PersoneelType] AS [ID-PersoneelType],
	[Werkgever],
	[WerkgeverBV] AS [BedrijfsID-WerkgeverBV],
	[Beroep],
	[CAO] AS [tblPersoneel.CAO],
	[ContractUren],
	[Initialen],
	[Voornaam],
	[Tussenvoegsel],
	[Achternaam],
	[Adres] AS [tblPersoneel.Adres],
	[Postcode] AS [tblPersoneel.Postcode],
	[Plaats] AS [tblPersoneel.Plaats],
	[Telefoon] AS [tblPersoneel.Telefoon],
	[Mobiel],
	[Email] AS [tblPersoneel.Email],
	[Actief] AS [tblPersoneel.Actief],
	[DatumUitDienst],
	[DatumInactiefGezet] AS [tblPersoneel.DatumInactiefGezet],
	[Aanmaakdatum] AS [tblPersoneel.Aanmaakdatum],
	[VolledigeNaam],
	[Gebruiker] AS [tblPersoneel.Gebruiker],
	[GebruikBijOverslag] AS [tblPersoneel.GebruikBijOverslag],
	[GebruikBijRit] AS [tblPersoneel.GebruikBijRit],
	[GebruikBijStrooien] AS [tblPersoneel.GebruikBijStrooien],
	[GebruikenBijRitUitvoerder],
	[DeltaOproepkracht],
	[UitlegUrenInvoer],
	[TariefIntern] AS [tblPersoneel.TariefIntern],
	[BSN],
	[SalarisFietsvergoeding],
	[SalarisBereikbaarheidsdienst],
	[SalarisVerschovenUren],
	[Ziek],
	[UserID],
	[Vrij],
	[TariefNieuw],
	[BeroepNieuw];
SELECT PersoneelID, 
	PersoneelNo, 
	PersoneelType, 
	Werkgever, 
	WerkgeverBV, 
	Beroep, 
	CAO, 
	ContractUren, 
	Initialen, 
	Voornaam, 
	Tussenvoegsel, 
	Achternaam, 
	Adres, 
	Postcode, 
	Plaats, 
	Telefoon, 
	Mobiel, 
	Email, 
	Actief, 
	DatumUitDienst, 
	DatumInactiefGezet, 
	Aanmaakdatum, 
	VolledigeNaam, 
	Gebruiker, 
	GebruikBijOverslag, 
	GebruikBijRit, 
	GebruikBijStrooien, 
	GebruikenBijRitUitvoerder, 
	DeltaOproepkracht, 
	UitlegUrenInvoer, 
	TariefIntern, 
	BSN, 
	SalarisFietsvergoeding, 
	SalarisBereikbaarheidsdienst, 
	SalarisVerschovenUren, 
	Ziek, 
	UserID, 
	Vrij, 
	TariefNieuw, 
	BeroepNieuw 
FROM "Sagro_backend".dbo.tblPersoneel;

[tblUrenRegistratieRegel]:
LOAD 
	[UrenregistratieRegelID],
	[DatumUrenReg] AS [DatumUrenReg-Yeardate],
	[PersoneelID],
	[ProjectNr] AS [ProjectNr-Werknummer],
	[Werkzaamheden],
	[OpdrachtID] AS [tblUrenRegistratieRegel.OpdrachtID],
	[MaterieelID],
	[HulpstukId],
	[HulpstukId2],
	[Uren],
	[Opmerking],
	[UrenCode],
	[Gebruiker] AS [tblUrenRegistratieRegel.Gebruiker],
	[Aanmaakdatum] AS [tblUrenRegistratieRegel.Aanmaakdatum],
	[NietFacturabel],
	[Toegevoegd],
	[ProjectNr2],
	[Kostendrager] AS [tblUrenRegistratieRegel.Kostendrager];
SELECT UrenregistratieRegelID, 
	DatumUrenReg, 
	PersoneelID, 
	ProjectNr, 
	Werkzaamheden, 
	OpdrachtID, 
	MaterieelID, 
	HulpstukId, 
	HulpstukId2, 
	Uren, 
	Opmerking, 
	UrenCode, 
	Gebruiker, 
	Aanmaakdatum, 
	NietFacturabel, 
	Toegevoegd, 
	ProjectNr2, 
	Kostendrager 
FROM "Sagro_backend".dbo.tblUrenRegistratieRegel;

[zLookupAlgemeen]:
LOAD 
	[ID] AS [ID-PersoneelType],
	[Type],
	[Waarde],
	[Waarde2],
	[Aanmaakdatum] AS [zLookupAlgemeen.Aanmaakdatum],
	[Locked];
SELECT ID, 
	Type, 
	Waarde, 
	Waarde2, 
	Aanmaakdatum, 
	Locked 
FROM "Sagro_backend".dbo.zLookupAlgemeen;

[zLookupBedrijven]:
LOAD 
	[BedrijfsID] AS [BedrijfsID-WerkgeverBV],
	[Bedrijfsnaam],
	[BvShortName],
	[ExactImportFolder],
	[ProjectCodePrefix],
	[PersoneelCodePrefix],
	[Logo],
	[CAO] AS [zLookupBedrijven.CAO],
	[Banknr],
	[Iban],
	[SWIFTcode],
	[KVKnr],
	[BTWnr],
	[SFBnr],
	[Adres] AS [zLookupBedrijven.Adres],
	[Postcode] AS [zLookupBedrijven.Postcode],
	[Plaats] AS [zLookupBedrijven.Plaats],
	[Telefoon] AS [zLookupBedrijven.Telefoon],
	[Fax],
	[TelefoonPlanning],
	[Website],
	[EANcode],
	[Zichtbaar],
	[Email] AS [zLookupBedrijven.Email],
	[BedrijfsnaamKort],
	[Aanmaakdatum] AS [zLookupBedrijven.Aanmaakdatum];
SELECT BedrijfsID, 
	Bedrijfsnaam, 
	BvShortName, 
	ExactImportFolder, 
	ProjectCodePrefix, 
	PersoneelCodePrefix, 
	Logo, 
	CAO, 
	Banknr, 
	Iban, 
	SWIFTcode, 
	KVKnr, 
	BTWnr, 
	SFBnr, 
	Adres, 
	Postcode, 
	Plaats, 
	Telefoon, 
	Fax, 
	TelefoonPlanning, 
	Website, 
	EANcode, 
	Zichtbaar, 
	Email, 
	BedrijfsnaamKort, 
	Aanmaakdatum 
FROM "Sagro_backend".dbo.zLookupBedrijven;

[zLookupYearDays]:
LOAD 
	[ID] AS [zLookupYearDays.ID],
	[Yeardate] AS [DatumUrenReg-Yeardate],
	[WeekNo],
	[WeekdayNo],
	[Weekday],
	[WeekFromTill],
	[WeekFirstDay],
	[WeekLastDay],
	[WeekDayRateType],
	[YeardateYear],
	[YeardateMonth],
	[YeardateMonthName],
	[YeardateDay],
	[IsFeestdag];
SELECT ID, 
	Yeardate, 
	WeekNo, 
	WeekdayNo, 
	Weekday, 
	WeekFromTill, 
	WeekFirstDay, 
	WeekLastDay, 
	WeekDayRateType, 
	YeardateYear, 
	YeardateMonth, 
	YeardateMonthName, 
	YeardateDay, 
	IsFeestdag 
FROM "Sagro_backend".dbo.zLookupYearDays;

[tblUrenregistratie]:
LOAD 
	[UrenregistratieID],
	[PersoneelID],
	Date([DatumUrenReg] ) AS [tblUrenregistratie.DatumUrenReg],
	[VertrekHeenreis],
	[AankomstHeenreis],
	[PauzeTijd],
	[VertrekTerugreis],
	[AankomstTerugreis],
	[Reistijd],
	[ReistijdEigenRekening],
	[TotaalWerktijd],
	[Uren100Procent],
	[Uren100ProcentOverwerk],
	[Uren125Procent],
	[Uren150Procent],
	[Uren200Procent],
	[KmZakelijk],
	[KmVergoeding],
	[UrenAsbest],
	[1daagseRitverg1],
	[1daagseRitverg2],
	[1daagseRitverg3],
	[Nachtritvergoeding],
	[Afwezigheidsvergoeding],
	[TvtToepassen],
	[UrenTvt100],
	[UrenTvt130],
	[UrenTvt150],
	[UrenTvt200],
	[DOenRuren75],
	[DOenRuren125],
	[DOenRuren150],
	[DOenRuren200],
	[Gebruiker],
	[Aanmaakdatum],
	[StrooiNettoVergoedingPerOproep],
	[StrooiNettoVergoedingUren1],
	[StrooiNettoVergoedingUren2],
	[StrooiNettoVergoedingUren3],
	[StrooienNettoVergoedingOnkosten1],
	[StrooienNettoVergoedingOnkosten2],
	[Fietsvergoeding],
	[Bereikbaarheidsdienst],
	[BereikbaarheidsdienstWeekend],
	[VerschovenUren30],
	[VerschovenUren50],
	[VerschovenUren75],
	[VerschovenUren100],
	[AfwezigheidsvergoedingTussenliggendeDagen],
	[SaveReistijdEigenRekening];
SELECT UrenregistratieID, 
	PersoneelID, 
	DatumUrenReg, 
	VertrekHeenreis, 
	AankomstHeenreis, 
	PauzeTijd, 
	VertrekTerugreis, 
	AankomstTerugreis, 
	Reistijd, 
	ReistijdEigenRekening, 
	TotaalWerktijd, 
	Uren100Procent, 
	Uren100ProcentOverwerk, 
	Uren125Procent, 
	Uren150Procent, 
	Uren200Procent, 
	KmZakelijk, 
	KmVergoeding, 
	UrenAsbest, 
	"1daagseRitverg1", 
	"1daagseRitverg2", 
	"1daagseRitverg3", 
	Nachtritvergoeding, 
	Afwezigheidsvergoeding, 
	TvtToepassen, 
	UrenTvt100, 
	UrenTvt130, 
	UrenTvt150, 
	UrenTvt200, 
	DOenRuren75, 
	DOenRuren125, 
	DOenRuren150, 
	DOenRuren200, 
	Gebruiker, 
	Aanmaakdatum, 
	StrooiNettoVergoedingPerOproep, 
	StrooiNettoVergoedingUren1, 
	StrooiNettoVergoedingUren2, 
	StrooiNettoVergoedingUren3, 
	StrooienNettoVergoedingOnkosten1, 
	StrooienNettoVergoedingOnkosten2, 
	Fietsvergoeding, 
	Bereikbaarheidsdienst, 
	BereikbaarheidsdienstWeekend, 
	VerschovenUren30, 
	VerschovenUren50, 
	VerschovenUren75, 
	VerschovenUren100, 
	AfwezigheidsvergoedingTussenliggendeDagen, 
	SaveReistijdEigenRekening 
FROM "Sagro_backend".dbo.tblUrenregistratie;

[tblRit]:
LOAD 
	[RitID],
	[PlanLocatie],
	[AantalRitten],
	[MaterieelID] AS [tblRit.MaterieelID],
	[PersoneelID],
	[OpdrachtID],
	[DebiteurCode] AS [tblRit.DebiteurCode],
	[Ritdatum],
	[TijdVertrek],
	[TijdLaden],
	[TijdLossen],
	[TijdRetour],
	[LadingOmschrijving],
	[RitType],
	[RitStatus],
	[LaadAdresNaam],
	[LaadAdresStraat],
	[LaadAdresPostcode],
	[LaadAdresPlaats],
	[LaadAdresLand],
	[LaadOpmerking],
	[LosAdresNaam],
	[LosAdresStraat],
	[LosAdresPostcode],
	[LosAdresPlaats],
	[LosAdresLand],
	[LosOpmerking],
	[OpmerkingChauffeur],
	[RitVoorParticulier],
	[KleurInTimeline],
	[Uitvoerder],
	[Aanmaakdatum] AS [tblRit.Aanmaakdatum],
	[Gebruiker] AS [tblRit.Gebruiker],
	[TotaalUren],
	[PauzeUren],
	[Tunnel],
	[Vracht],
	[VrachtUnit] AS [UnitID-VrachtUnit],
	[RitKeuze],
	[RitBegin],
	[MaterieelOplegger],
	[RitEinde],
	[Bonnummer],
	[Tarief],
	APPLYMAP( '__countryCodeIsoTwo2Polygon', UPPER([LaadAdresLand]), '-') AS [tblRit.LaadAdresLand_GeoInfo],
	APPLYMAP( '__countryCodeIsoTwo2Polygon', UPPER([LosAdresLand]), '-') AS [tblRit.LosAdresLand_GeoInfo];
SELECT RitID, 
	PlanLocatie, 
	AantalRitten, 
	MaterieelID, 
	PersoneelID, 
	OpdrachtID, 
	DebiteurCode, 
	Ritdatum, 
	TijdVertrek, 
	TijdLaden, 
	TijdLossen, 
	TijdRetour, 
	LadingOmschrijving, 
	RitType, 
	RitStatus, 
	LaadAdresNaam, 
	LaadAdresStraat, 
	LaadAdresPostcode, 
	LaadAdresPlaats, 
	LaadAdresLand, 
	LaadOpmerking, 
	LosAdresNaam, 
	LosAdresStraat, 
	LosAdresPostcode, 
	LosAdresPlaats, 
	LosAdresLand, 
	LosOpmerking, 
	OpmerkingChauffeur, 
	RitVoorParticulier, 
	KleurInTimeline, 
	Uitvoerder, 
	Aanmaakdatum, 
	Gebruiker, 
	TotaalUren, 
	PauzeUren, 
	Tunnel, 
	Vracht, 
	VrachtUnit, 
	RitKeuze, 
	RitBegin, 
	MaterieelOplegger, 
	RitEinde, 
	Bonnummer, 
	Tarief 
FROM "Sagro_backend".dbo.tblRit;

[tblUnit]:
LOAD 
	[UnitID] AS [UnitID-VrachtUnit],
	[Unit],
	[UseInRitPlanning];
SELECT UnitID, 
	Unit, 
	UseInRitPlanning 
FROM "Sagro_backend".dbo.tblUnit;

TAG FIELD [LaadAdresLand] WITH "$geoname" ;
TAG FIELD [tblRit.LaadAdresLand_GeoInfo] WITH "$geopolygon" ;
TAG FIELD [LosAdresLand] WITH "$geoname" ;
TAG FIELD [tblRit.LosAdresLand_GeoInfo] WITH "$geopolygon" ;

DROP TABLES __countryGeoBase;
[autoCalendar]: 
  DECLARE FIELD DEFINITION Tagged ('$date')
FIELDS
  Dual(Year($1), YearStart($1)) AS [Year] Tagged ('$axis', '$year'),
  Dual('Q'&Num(Ceil(Num(Month($1))/3)),Num(Ceil(NUM(Month($1))/3),00)) AS [Quarter] Tagged ('$quarter', '$cyclic'),
  Dual(Year($1)&'-Q'&Num(Ceil(Num(Month($1))/3)),QuarterStart($1)) AS [YearQuarter] Tagged ('$yearquarter', '$qualified'),
  Dual('Q'&Num(Ceil(Num(Month($1))/3)),QuarterStart($1)) AS [_YearQuarter] Tagged ('$yearquarter', '$hidden', '$simplified'),
  Month($1) AS [Month] Tagged ('$month', '$cyclic'),
  Dual(Year($1)&'-'&Month($1), monthstart($1)) AS [YearMonth] Tagged ('$axis', '$yearmonth', '$qualified'),
  Dual(Month($1), monthstart($1)) AS [_YearMonth] Tagged ('$axis', '$yearmonth', '$simplified', '$hidden'),
  Dual('W'&Num(Week($1),00), Num(Week($1),00)) AS [Week] Tagged ('$weeknumber', '$cyclic'),
  Date(Floor($1)) AS [Date] Tagged ('$axis', '$date', '$qualified'),
  Date(Floor($1), 'D') AS [_Date] Tagged ('$axis', '$date', '$hidden', '$simplified');

DERIVE FIELDS FROM FIELDS [tblMaterieel.Aanmaakdatum], [VerkoopDatum], [Bouwdatum], [OpdrachtDatum], [OpdrachtEindDatum], [tblOpdracht.Aanmaakdatum], [DatumUitDienst], [tblPersoneel.DatumInactiefGezet], [tblPersoneel.Aanmaakdatum], [DatumUrenReg-Yeardate], [tblUrenRegistratieRegel.Aanmaakdatum], [zLookupAlgemeen.Aanmaakdatum], [zLookupBedrijven.Aanmaakdatum], [WeekFirstDay], [WeekLastDay], [tblUrenregistratie.DatumUrenReg], [Aanmaakdatum], [Ritdatum], [tblRit.Aanmaakdatum] USING [autoCalendar] ;